export default {
  hero: { line1: 'Suscripciones Globales', line2: 'Ahora Más Sencillas', subtitle: 'Una plataforma de tarjetas virtuales multidivisa para publicidad, servicios en la nube y suscripciones internacionales', openCard: 'Solicitar una Tarjeta' },
  payment: { title: 'Pagos Transfronterizos · Gestión en un Solo Lugar', subtitle: 'Escenarios de gasto habituales · Gestión flexible de varias tarjetas · Liquidación multidivisa sencilla' },
  security: { title: 'Tasas transparentes · Registros de fondos claros', subtitle: 'Estructura de tarifas clara · Registros rastreables · Operaciones responsables', viewMore: 'Ver más' },
  scenarios: { title: 'Escenarios comunes · Cobertura amplia', subtitle: 'Apoyo a la publicidad común, servicio en la nube y escenarios de suscripción global' },
  onboarding: { title: 'Crear una Cuenta · Empezar', subtitle: 'Solicite y utilice una tarjeta virtual en tres pasos', register: 'Crear Cuenta', registerDesc: 'Introduzca la información necesaria para crear su cuenta.', verify: 'Verificar Identidad', verifyDesc: 'Envíe la información necesaria y espere el resultado de la revisión.', createCard: 'Solicitar una Tarjeta', createCardDesc: 'Tras la aprobación, solicite una tarjeta y establezca su límite.', join: 'Empezar', registerNow: 'Registrarse Ahora', verifyNow: 'Verificar Ahora', openCardNow: 'Solicitar una Tarjeta', openCardAgain: 'Solicitar Otra Tarjeta', completed: 'Completado', pending: 'Pendiente' },
  benefits: [{ title: 'Gestión Flexible de Tarjetas', desc: 'Las solicitudes de varias tarjetas ayudan a los equipos a gestionar con claridad los presupuestos de sus proyectos.' }, { title: 'Integración con API Abierta', desc: 'Las API estandarizadas facilitan la integración con los sistemas empresariales.' }, { title: 'Operaciones de Agentes', desc: 'Admite operaciones de marca y una gestión trazable del reparto de ingresos.' }, { title: 'Optimización Continua de Pagos', desc: 'La colaboración en el control de riesgos ayuda a mejorar la disponibilidad de los servicios de pago.' }, { title: 'Registros de Fondos Claros', desc: 'Los registros centralizados de fondos facilitan la revisión y la conciliación.' }],
  paymentFeatures: [{ title: 'Escenarios de Gasto Habituales', desc: 'Adecuado para determinadas plataformas publicitarias, suscripciones de IA y SaaS, servicios en la nube y suscripciones internacionales. La disponibilidad depende de los detalles del BIN de tarjeta y de las reglas del comercio.' }, { title: 'Varias Tarjetas Configurables', desc: 'Solicite tarjetas virtuales por proyecto, cuenta o finalidad y configure límites dentro de las reglas aplicables.' }, { title: 'Liquidación Multidivisa Sencilla', desc: 'Admite determinadas divisas principales. Los tipos de cambio, las comisiones y los resultados contables dependen de los pedidos y registros del servidor.' }],
  metrics: ['Usuarios registrados', 'Socios comerciales', 'Países o regiones', 'Transacciones (millones)'],
  safeguards: [{ title: 'Tasas transparentes', items: ['Los cargos de apertura y transacción aplicables se muestran claramente', 'Los cambios en los fondos incluyen registros para el examen y la localización', 'Los cargos finales dependen del cálculo del orden y del lado del servidor'] }, { title: 'Administración de fondos', items: ['Los fondos son procesados por los bancos o instituciones asociados aplicables conforme a las normas pertinentes', 'Los fondos operativos y clientes se gestionan según los requisitos aplicables', 'Los registros de fondos se muestran y concilian por cuenta'] }, { title: 'Medidas de seguridad', items: ['Las salvaguardias pertinentes se aplican sobre la base de los requisitos bancarios y asociados', 'Los mecanismos de vigilancia del riesgo ayudan a abordar la actividad inusual', 'Las medidas sensibles exigen la verificación de identidad y seguridad aplicables'] }, { title: 'Operaciones responsables', items: ['Los servicios se prestan de acuerdo con los requisitos de calificación y licencias aplicables', 'Se siguen los requisitos de banca aplicable, AML, KYC y regulación', 'Los procesos institucionales y los controles de riesgo se mejoran continuamente'] }],
}
