export default {
  hero: { line1: 'Abonnements Internationaux', line2: 'Désormais Plus Simples', subtitle: 'Une plateforme de cartes virtuelles multidevises pour la publicité, les services cloud et les abonnements internationaux', openCard: 'Demander une Carte' },
  payment: { title: 'Paiements Transfrontaliers · Gestion Centralisée', subtitle: 'Scénarios de dépenses courants · Gestion flexible de plusieurs cartes · Règlement multidevise simplifié' },
  security: { title: 'Frais Transparents · Registres de Fonds Clairs', subtitle: 'Structure tarifaire claire · Registres traçables · Opérations responsables', viewMore: 'En Savoir Plus' },
  scenarios: { title: 'Scénarios communs · Couverture générale', subtitle: 'Soutien à la publicité commune, au service cloud et aux scénarios d\'abonnement mondiaux' },
  onboarding: { title: 'Créer un compte · Commencer', subtitle: 'Demander et utiliser une carte virtuelle en trois étapes', register: 'Créer un compte', registerDesc: 'Saisissez les informations requises pour créer votre compte.', verify: 'Vérification de l\'identité', verifyDesc: 'Soumettre les renseignements requis et attendre le résultat de l\'examen.', createCard: 'Demander une carte', createCardDesc: 'Après approbation, demander une carte et fixer sa limite.', join: 'Commencez', registerNow: 'Inscrivez-vous maintenant', verifyNow: 'Vérifiez maintenant', openCardNow: 'Ouvrez une carte maintenant', openCardAgain: 'Ouvrir à nouveau la carte', completed: 'Achevé', pending: 'En attente' },
  benefits: [{ title: 'Gestion Flexible des Cartes', desc: 'Les demandes de plusieurs cartes aident les équipes à gérer clairement les budgets des projets.' }, { title: 'Intégration par API Ouverte', desc: 'Les API normalisées facilitent l’intégration avec les systèmes métier.' }, { title: 'Opérations des Agents', desc: 'Prise en charge des opérations de marque et d’une gestion traçable du partage des revenus.' }, { title: 'Optimisation Continue des Paiements', desc: 'La collaboration en matière de contrôle des risques contribue à améliorer la disponibilité des services de paiement.' }, { title: 'Registres de Fonds Clairs', desc: 'Les registres de fonds centralisés facilitent l’analyse et le rapprochement.' }],
  paymentFeatures: [{ title: 'Scénarios de Dépenses Courants', desc: 'Convient à certaines plateformes publicitaires, aux abonnements d’IA et SaaS, aux services cloud et aux abonnements internationaux. La disponibilité dépend des détails du BIN de carte et des règles du commerçant.' }, { title: 'Plusieurs Cartes Configurables', desc: 'Demandez des cartes virtuelles par projet, compte ou objectif et définissez les limites dans le cadre des règles applicables.' }, { title: 'Règlement Multidevise Simplifié', desc: 'Prend en charge certaines devises principales. Les taux de change, les frais et les résultats comptables dépendent des commandes et des enregistrements du serveur.' }],
  metrics: ['Utilisateurs enregistrés', 'Partenaires commerciaux', 'Pays ou régions', 'Opérations (en millions)'],
  safeguards: [{ title: 'Frais Transparents', items: ['Les frais applicables à l’émission des cartes et aux transactions sont clairement indiqués.', 'Les variations de fonds sont enregistrées à des fins de vérification et de suivi', 'Les frais définitifs dépendent de la commande et du calcul effectué côté serveur'] }, { title: 'Gestion des Fonds', items: ['Les fonds sont traités par des banques ou institutions partenaires éligibles conformément aux règles applicables', 'Les fonds opérationnels et les fonds des clients sont gérés conformément aux exigences applicables', 'Les registres de fonds sont affichés et rapprochés par compte'] }, { title: 'Mesures de Sécurité', items: ['Les protections nécessaires sont appliquées selon les exigences des banques et des partenaires', 'Les mécanismes de surveillance des risques aident à détecter les activités inhabituelles', 'Les opérations sensibles nécessitent une vérification valide de l’identité et de la sécurité'] }, { title: 'Opérations Responsables', items: ['Les services sont fournis conformément aux exigences applicables de qualification et de licence', 'Les exigences bancaires, AML, KYC et réglementaires applicables sont respectées', 'Les processus opérationnels et les contrôles des risques sont continuellement améliorés'] }],
}
