export default {
  hero: { line1: 'Subscrições Globais', line2: 'Agora Mais Simples', subtitle: 'Uma plataforma de cartões virtuais multimoeda para publicidade, serviços na nuvem e subscrições internacionais', openCard: 'Solicitar Cartão' },
  payment: { title: 'Pagamentos Transfronteiriços · Gestão num Só Lugar', subtitle: 'Cenários de despesa comuns · Gestão flexível de vários cartões · Liquidação multimoeda simples' },
  security: { title: 'Taxas Transparentes · Registos de Fundos Claros', subtitle: 'Estrutura de taxas clara · Registos rastreáveis · Operações responsáveis', viewMore: 'Ver Mais' },
  scenarios: { title: 'Cenários Comuns · Cobertura Alargada', subtitle: 'Apoio a cenários comuns de publicidade, serviços na nuvem e subscrições globais' },
  onboarding: { title: 'Criar Conta · Começar a Utilizar', subtitle: 'Solicite e utilize um cartão virtual em três passos', register: 'Criar Conta', registerDesc: 'Introduza as informações necessárias para criar a sua conta.', verify: 'Verificar Identidade', verifyDesc: 'Envie as informações necessárias e aguarde o resultado da análise.', createCard: 'Solicitar Cartão', createCardDesc: 'Após a aprovação, solicite um cartão e defina o respetivo limite.', join: 'Começar', registerNow: 'Registar Agora', verifyNow: 'Verificar Agora', openCardNow: 'Solicitar Cartão', openCardAgain: 'Solicitar Outro Cartão', completed: 'Concluído', pending: 'Pendente' },
  benefits: [{ title: 'Gestão Flexível de Cartões', desc: 'Os pedidos de vários cartões ajudam as equipas a gerir claramente os orçamentos dos projetos.' }, { title: 'Integração por API Aberta', desc: 'As APIs normalizadas permitem a integração com sistemas empresariais.' }, { title: 'Operações de Agentes', desc: 'Apoio a operações de marca e gestão rastreável da partilha de receitas.' }, { title: 'Otimização Contínua de Pagamentos', desc: 'A colaboração no controlo de risco ajuda a melhorar a disponibilidade dos serviços de pagamento.' }, { title: 'Registos de Fundos Claros', desc: 'Os registos de fundos centralizados apoiam a análise e a reconciliação.' }],
  paymentFeatures: [{ title: 'Cenários de Despesa Comuns', desc: 'Adequado para plataformas de publicidade selecionadas, subscrições de IA e SaaS, serviços na nuvem e subscrições internacionais. A disponibilidade depende dos detalhes do BIN do cartão e das regras do comerciante.' }, { title: 'Vários Cartões Configuráveis', desc: 'Solicite cartões virtuais por projeto, conta ou finalidade e defina limites dentro das regras aplicáveis.' }, { title: 'Liquidação Multimoeda Simples', desc: 'Suporta determinadas moedas principais. As taxas de câmbio, comissões e resultados de registo dependem das encomendas e dos registos do servidor.' }],
  metrics: ['Utilizadores registados', 'Parceiros comerciais', 'Países ou Regiões', 'Operações (milhões)'],
  safeguards: [{ title: 'Taxas Transparentes', items: ['As taxas aplicáveis à emissão de cartões e às transações são apresentadas de forma clara', 'As alterações de fundos ficam registadas para análise e rastreio', 'As taxas finais dependem da encomenda e do cálculo efetuado no servidor'] }, { title: 'Gestão de Fundos', items: ['Os fundos são processados por bancos ou instituições parceiras elegíveis ao abrigo das regras aplicáveis', 'Os fundos operacionais e dos clientes são geridos de acordo com os requisitos aplicáveis', 'Os registos de fundos são apresentados e reconciliados por conta'] }, { title: 'Medidas de Segurança', items: ['As salvaguardas relevantes são aplicadas de acordo com os requisitos dos bancos e parceiros', 'Os mecanismos de monitorização de risco ajudam a detetar atividades pouco habituais', 'As ações sensíveis exigem verificação de identidade e segurança válida'] }, { title: 'Operações Responsáveis', items: ['Os serviços são prestados de acordo com os requisitos de qualificação e licenciamento aplicáveis', 'São cumpridos os requisitos bancários, AML, KYC e regulamentares aplicáveis', 'Os processos de negócio e os controlos de risco são continuamente melhorados'] }],
}
