export default {
  hero: { line1: 'Küresel Abonelikler', line2: 'Artık Daha Kolay', subtitle: 'Reklam, bulut hizmetleri ve sınır ötesi abonelikler için çok para birimli sanal kart platformu', openCard: 'Kart Başvurusu Yap' },
  payment: { title: 'Sınır Ötesi Ödemeler · Tek Noktadan Yönetim', subtitle: 'Yaygın harcama senaryoları · Esnek toplu kart yönetimi · Kolay çok para birimli mutabakat' },
  security: { title: 'Şeffaf Ücretler · Açık Fon Kayıtları', subtitle: 'Şeffaf ücret yapısı · İzlenebilir kayıtlar · Sorumlu operasyonlar', viewMore: 'Daha Fazla Bilgi' },
  scenarios: { title: 'Yaygın Senaryolar · Geniş Kapsam', subtitle: 'Yaygın reklam, bulut hizmeti ve küresel abonelik senaryolarını destekler' },
  onboarding: { title: 'Hesap Oluşturun · Kullanmaya Başlayın', subtitle: 'Üç adımda sanal kart başvurusu yapın ve kullanmaya başlayın', register: 'Hesap Oluştur', registerDesc: 'Hesabınızı oluşturmak için gerekli bilgileri girin.', verify: 'Kimliğinizi Doğrulayın', verifyDesc: 'Gerekli bilgileri gönderin ve inceleme sonucunu bekleyin.', createCard: 'Kart Başvurusu Yapın', createCardDesc: 'Onaylandıktan sonra kart başvurusu yapın ve limitini belirleyin.', join: 'Başlayın', registerNow: 'Şimdi Kaydolun', verifyNow: 'Şimdi Doğrulayın', openCardNow: 'Kart Başvurusu Yapın', openCardAgain: 'Başka Bir Kart Açın', completed: 'Tamamlandı', pending: 'Bekliyor' },
  benefits: [{ title: 'Esnek Kart Yönetimi', desc: 'Toplu kart başvuruları, ekiplerin proje bütçelerini açık biçimde yönetmesine yardımcı olur.' }, { title: 'Açık API Entegrasyonu', desc: 'Standart API’ler, iş sistemlerinizle entegrasyonu destekler.' }, { title: 'Temsilci Operasyonları', desc: 'Markalı operasyonları ve izlenebilir gelir paylaşımı yönetimini destekler.' }, { title: 'Sürekli Ödeme Optimizasyonu', desc: 'Risk kontrolü iş birliği, ödeme hizmetlerinin kullanılabilirliğini geliştirmeye yardımcı olur.' }, { title: 'Açık Fon Kayıtları', desc: 'Merkezi fon kayıtları, inceleme ve mutabakat süreçlerini destekler.' }],
  paymentFeatures: [{ title: 'Yaygın Harcama Senaryoları', desc: 'Seçili reklam platformları, AI ve SaaS abonelikleri, bulut hizmetleri ve uluslararası abonelikler için uygundur. Kullanılabilirlik, Kart BIN ayrıntılarına ve iş yeri kurallarına bağlıdır.' }, { title: 'Yapılandırılabilir Toplu Kartlar', desc: 'Sanal kartları proje, hesap veya amaca göre yönetin ve geçerli kurallar kapsamında limit belirleyin.' }, { title: 'Çok Para Birimli Mutabakat', desc: 'Seçili başlıca para birimlerini destekler. Döviz kurları, ücretler ve kayıt sonuçları sipariş ve sunucu kayıtlarına bağlıdır.' }],
  metrics: ['Kayıtlı Kullanıcılar', 'İş Ortakları', 'Ülkeler veya Bölgeler', 'İşlemler (Milyon)'],
  safeguards: [{ title: 'Şeffaf Ücretler', items: ['Geçerli kart açma ve işlem ücretleri açıkça gösterilir', 'Fon değişiklikleri, inceleme ve izleme için kaydedilir', 'Nihai ücretler siparişe ve sunucu tarafındaki hesaplamaya bağlıdır'] }, { title: 'Fon Yönetimi', items: ['Fonlar, ilgili kurallar kapsamında uygun iş ortağı bankalar veya kurumlar tarafından işlenir', 'İşletme ve müşteri fonları, geçerli koşullara göre yönetilir', 'Fon kayıtları hesapta görüntülenir ve mutabakata tabi tutulur'] }, { title: 'Güvenlik Önlemleri', items: ['İlgili korumalar banka ve iş ortağı gereksinimlerine göre uygulanır', 'Risk mekanizmaları olağan dışı etkinliklerin belirlenmesine yardımcı olur', 'Hassas işlemler, geçerli kimlik ve güvenlik doğrulaması gerektirir'] }, { title: 'Sorumlu Operasyonlar', items: ['Hizmetler, geçerli yeterlilik ve lisans gereksinimlerine göre sunulur', 'Geçerli bankacılık, AML, KYC ve düzenleyici gereksinimler izlenir', 'İş süreçleri ve risk kontrolleri sürekli geliştirilir'] }],
}
