export default {
  hero: { line1: 'Đăng ký Toàn cầu', line2: 'Nay Dễ dàng Hơn', subtitle: 'Nền tảng thẻ ảo đa tiền tệ dành cho quảng cáo, dịch vụ đám mây và đăng ký quốc tế', openCard: 'Đăng ký Thẻ' },
  payment: { title: 'Thanh toán Xuyên biên giới · Quản lý Tập trung', subtitle: 'Tình huống chi tiêu phổ biến · Quản lý nhiều thẻ linh hoạt · Quyết toán đa tiền tệ thuận tiện' },
  security: { title: 'Phí Minh bạch · Hồ sơ Tài chính Rõ ràng', subtitle: 'Cơ cấu phí rõ ràng · Hồ sơ có thể theo dõi · Vận hành có trách nhiệm', viewMore: 'Xem thêm' },
  scenarios: { title: 'Tình huống Phổ biến · Phạm vi Rộng', subtitle: 'Hỗ trợ các tình huống phổ biến về quảng cáo, dịch vụ đám mây và đăng ký toàn cầu' },
  onboarding: { title: 'Tạo tài khoản và bắt đầu', subtitle: 'Đăng ký và sử dụng thẻ ảo chỉ trong ba bước', register: 'Tạo tài khoản', registerDesc: 'Nhập thông tin cần thiết để tạo tài khoản.', verify: 'Xác minh danh tính', verifyDesc: 'Gửi thông tin được yêu cầu và chờ kết quả xem xét.', createCard: 'Đăng ký thẻ', createCardDesc: 'Sau khi được phê duyệt, hãy gửi yêu cầu mở thẻ và đặt hạn mức.', join: 'Bắt đầu', registerNow: 'Đăng ký ngay', verifyNow: 'Xác minh ngay', openCardNow: 'Mở thẻ ngay', openCardAgain: 'Mở thêm thẻ', completed: 'Đã hoàn tất', pending: 'Đang chờ' },
  benefits: [{ title: 'Quản lý Thẻ Linh hoạt', desc: 'Đăng ký nhiều thẻ giúp các nhóm quản lý ngân sách dự án một cách rõ ràng.' }, { title: 'Tích hợp API Mở', desc: 'API tiêu chuẩn hỗ trợ tích hợp với các hệ thống kinh doanh.' }, { title: 'Vận hành Đại lý', desc: 'Hỗ trợ vận hành theo thương hiệu riêng và quản lý chia sẻ doanh thu có thể theo dõi.' }, { title: 'Tối ưu Thanh toán Liên tục', desc: 'Hợp tác kiểm soát rủi ro giúp cải thiện khả năng sử dụng dịch vụ thanh toán.' }, { title: 'Hồ sơ Tài chính Rõ ràng', desc: 'Hồ sơ tài chính tập trung hỗ trợ việc xem xét và đối soát.' }],
  paymentFeatures: [{ title: 'Tình huống Chi tiêu Phổ biến', desc: 'Phù hợp với một số nền tảng quảng cáo, gói đăng ký AI và SaaS, dịch vụ đám mây và đăng ký quốc tế. Khả năng sử dụng phụ thuộc vào chi tiết BIN thẻ và quy tắc của đơn vị chấp nhận thẻ.' }, { title: 'Nhiều Thẻ Có thể Cấu hình', desc: 'Đăng ký thẻ ảo theo dự án, tài khoản hoặc mục đích và thiết lập hạn mức trong phạm vi quy tắc áp dụng.' }, { title: 'Quyết toán Đa tiền tệ Thuận tiện', desc: 'Hỗ trợ một số loại tiền tệ chính. Tỷ giá, phí và kết quả ghi nhận phụ thuộc vào đơn hàng và hồ sơ máy chủ.' }],
  metrics: ['Người dùng Đã đăng ký', 'Đối tác Kinh doanh', 'Quốc gia hoặc Khu vực', 'Giao dịch (Triệu)'],
  safeguards: [{ title: 'Phí Minh bạch', items: ['Phí phát hành thẻ và phí giao dịch áp dụng được hiển thị rõ ràng', 'Biến động tài chính được ghi lại để xem xét và theo dõi', 'Mức phí cuối cùng phụ thuộc vào đơn hàng và kết quả tính toán phía máy chủ'] }, { title: 'Quản lý Tài chính', items: ['Tài chính được xử lý bởi ngân hàng hoặc tổ chức đối tác đủ điều kiện theo các quy tắc liên quan', 'Tài chính vận hành và tài chính của khách hàng được quản lý theo yêu cầu áp dụng', 'Hồ sơ tài chính được hiển thị và đối soát theo tài khoản'] }, { title: 'Biện pháp Bảo mật', items: ['Các biện pháp bảo vệ cần thiết được áp dụng theo yêu cầu của ngân hàng và đối tác', 'Cơ chế giám sát rủi ro giúp phát hiện hoạt động bất thường', 'Thao tác nhạy cảm yêu cầu xác minh danh tính và bảo mật hợp lệ'] }, { title: 'Vận hành Có trách nhiệm', items: ['Dịch vụ được cung cấp theo yêu cầu về năng lực và giấy phép áp dụng', 'Các yêu cầu về ngân hàng, AML, KYC và quy định áp dụng được tuân thủ', 'Quy trình kinh doanh và kiểm soát rủi ro được cải thiện liên tục'] }],
}
