export default {
  hero: { line1: 'Langganan Global', line2: 'Kini Lebih Mudah', subtitle: 'Platform kartu virtual berbagai mata uang untuk periklanan, layanan cloud, dan langganan internasional', openCard: 'Ajukan Kartu Sekarang' },
  payment: { title: 'Pembayaran Lintas Batas · Kelola di Satu Tempat', subtitle: 'Skenario pengeluaran umum · Pengelolaan banyak kartu yang fleksibel · Penyelesaian berbagai mata uang' },
  security: { title: 'Biaya Transparan · Catatan Dana yang Jelas', subtitle: 'Struktur biaya yang jelas · Catatan yang dapat dilacak · Operasi yang bertanggung jawab', viewMore: 'Lihat Selengkapnya' },
  scenarios: { title: 'Skenario Umum · Cakupan Luas', subtitle: 'Mendukung skenario periklanan, layanan cloud, dan langganan global yang umum' },
  onboarding: { title: 'Buat Akun · Mulai Gunakan', subtitle: 'Ajukan dan gunakan kartu virtual dalam tiga langkah', register: 'Buat Akun', registerDesc: 'Masukkan informasi yang diperlukan untuk membuat akun Anda.', verify: 'Verifikasi Identitas', verifyDesc: 'Kirim informasi yang diperlukan dan tunggu hasil tinjauan.', createCard: 'Ajukan Kartu', createCardDesc: 'Setelah disetujui, ajukan kartu dan tentukan batasnya.', join: 'Mulai', registerNow: 'Daftar Sekarang', verifyNow: 'Verifikasi Sekarang', openCardNow: 'Ajukan Kartu Sekarang', openCardAgain: 'Ajukan Kartu Lain', completed: 'Selesai', pending: 'Menunggu' },
  benefits: [{ title: 'Pengelolaan Kartu yang Fleksibel', desc: 'Pengajuan banyak kartu membantu tim mengelola anggaran proyek secara jelas.' }, { title: 'Integrasi API Terbuka', desc: 'API standar mendukung integrasi dengan sistem bisnis.' }, { title: 'Operasi Agen', desc: 'Mendukung operasi bermerek dan pengelolaan bagi hasil yang dapat dilacak.' }, { title: 'Optimalisasi Pembayaran Berkelanjutan', desc: 'Kolaborasi pengendalian risiko membantu meningkatkan ketersediaan layanan pembayaran.' }, { title: 'Catatan Dana yang Jelas', desc: 'Catatan dana terpusat mendukung peninjauan dan rekonsiliasi.' }],
  paymentFeatures: [{ title: 'Skenario Pengeluaran Umum', desc: 'Cocok untuk platform iklan tertentu, langganan AI dan SaaS, layanan cloud, serta langganan internasional. Ketersediaan mengikuti detail BIN kartu dan aturan merchant.' }, { title: 'Pengelolaan Banyak Kartu', desc: 'Kelola kartu virtual berdasarkan proyek, akun, atau tujuan, serta tetapkan batas sesuai aturan yang berlaku.' }, { title: 'Penyelesaian Berbagai Mata Uang', desc: 'Mendukung mata uang utama tertentu. Nilai tukar, biaya, dan hasil pembukuan mengikuti pesanan serta catatan server.' }],
  metrics: ['Pengguna Terdaftar', 'Mitra Bisnis', 'Negara atau Wilayah', 'Transaksi (Juta)'],
  safeguards: [{ title: 'Biaya Transparan', items: ['Biaya penerbitan kartu dan transaksi yang berlaku ditampilkan dengan jelas', 'Perubahan dana dicatat untuk peninjauan dan pelacakan', 'Biaya akhir bergantung pada pesanan dan hasil perhitungan di sisi server'] }, { title: 'Pengelolaan Dana', items: ['Dana diproses oleh bank atau lembaga mitra yang memenuhi syarat berdasarkan aturan terkait', 'Dana operasional dan dana pelanggan dikelola sesuai persyaratan yang berlaku', 'Catatan dana ditampilkan dan direkonsiliasi berdasarkan akun'] }, { title: 'Langkah Keamanan', items: ['Perlindungan terkait diterapkan berdasarkan persyaratan bank dan mitra', 'Mekanisme pemantauan risiko membantu mendeteksi aktivitas yang tidak biasa', 'Tindakan sensitif memerlukan verifikasi identitas dan keamanan yang berlaku'] }, { title: 'Operasi Bertanggung Jawab', items: ['Layanan disediakan sesuai persyaratan kualifikasi dan perizinan yang berlaku', 'Persyaratan perbankan, AML, KYC, dan regulasi yang berlaku dipatuhi', 'Proses bisnis dan pengendalian risiko terus ditingkatkan'] }],
}
