export default {
  hero: { line1: 'Global Subscriptions', line2: 'Made Easier', subtitle: 'Supporting virtual card solutions for advertising, cloud services, and cross-border subscription payments.', openCard: 'Issue a Card' },
  payment: { title: 'Cross-Border Payments • Centralized Card Management', subtitle: 'Major spending scenarios · Flexible bulk card management · Convenient multi-currency settlement' },
  security: { title: 'Transparent Fees · Clear Fund Records', subtitle: 'Clear fee structure · Traceable records · Responsible operations', viewMore: 'View More' },
  scenarios: { title: 'Business Use Cases • Broad Coverage', subtitle: 'Designed for digital advertising, cloud services, AI platforms, and global subscription payments.' },
  onboarding: { title: 'Create an Account · Get Started', subtitle: 'Get started with virtual cards in three easy steps', register: 'Create Account', registerDesc: 'Enter the required information to create your account.', verify: 'Identity Verification', verifyDesc: 'Complete identity verification and compliance review.', createCard: 'Start Issuing Cards', createCardDesc: 'Issue virtual cards and configure spending limits after approval.', join: 'Get Started', registerNow: 'Register Now', verifyNow: 'Verify Now', openCardNow: 'Issue a Card', openCardAgain: 'Issue Another Card', completed: 'Completed', pending: 'Pending' },
  benefits: [{ title: 'Flexible Card Management', desc: 'Bulk card applications help teams manage project budgets clearly.' }, { title: 'Open API Integration', desc: 'Standardized APIs support integration with business systems.' }, { title: 'Agent Operations', desc: 'Support for branded operations and traceable revenue-sharing management.' }, { title: 'Ongoing Payment Optimization', desc: 'Risk-control collaboration helps improve payment-service availability.' }, { title: 'Clear Fund Records', desc: 'Centralized fund records support review and reconciliation.' }],
  paymentFeatures: [{ title: 'Common Spending Scenarios', desc: 'Designed for digital advertising, AI & SaaS subscriptions, cloud services, and international subscription payments, with broad merchant acceptance. Availability depends on Card BIN details and merchant rules.' }, { title: 'Configurable Bulk Cards', desc: 'Issue virtual cards in bulk by Project, Account, or Business unit, with configurable limits within applicable rules.' }, { title: 'Convenient Multi-currency Settlement', desc: 'Support payments in major global currencies. Exchange rates, fees, and settlement results are subject to transaction and system records.' }],
  metrics: ['Registered Users', 'Business Partners', 'Countries or Regions', 'Transactions (Millions)'],
  safeguards: [{ title: 'Transparent Fees', items: ['Applicable card-opening and transaction fees are displayed clearly', 'Fund changes include records for review and tracing', 'Final fees depend on the order and server-side calculation'] }, { title: 'Fund Management', items: ['Funds are processed by applicable partner banks or institutions under relevant rules', 'Operating and customer funds are managed according to applicable requirements', 'Fund records are displayed and reconciled by account'] }, { title: 'Security Measures', items: ['Relevant safeguards are applied based on bank and partner requirements', 'Risk-monitoring mechanisms help address unusual activity', 'Sensitive actions require applicable identity and security verification'] }, { title: 'Responsible Operations', items: ['Services are provided according to applicable qualification and licensing requirements', 'Applicable banking, AML, KYC, and regulatory requirements are followed', 'Business processes and risk controls are continuously improved'] }],
}
