export default {
  verificationRequired: 'Bind and activate your email or Google Authenticator before continuing.',
  singleLoginEnabled: 'Single-login mode enabled successfully',
  singleLoginDisabled: 'Single-login mode disabled successfully',
  singleLoginFailed: 'Unable to update the single-login setting. Please try again later.',
  centerTitle: 'Security Center',
  overview: {
    description: 'Manage login verification, device restrictions, and two-factor authentication methods.', currentLevel: 'Current Security Level', progress: 'Security Progress', itemCount: '{count} items', levelHigh: 'High', levelMedium: 'Medium', levelLow: 'Low',
    loginConfig: 'Login Settings', loginConfigDesc: 'Manage account passwords, device restrictions, and login access controls.', viewDevices: 'View Login Devices', loginPassword: 'Login Password', loginPasswordDesc: 'Used to verify access when signing in', change: 'Change',
    singleLogin: 'Single Login', singleLoginOnDesc: 'This account can be signed in on only one device at a time', singleLoginOffDesc: 'This account can be signed in on multiple devices at the same time', enabled: 'Enabled', disabled: 'Disabled', enable: 'Enable', disable: 'Disable',
    ipWhitelist: 'IP Whitelist', ipSetDesc: 'Only IP addresses on the allowlist can sign in', ipUnsetDesc: 'Restrict common login sources to reduce unauthorized-access risk', set: 'Set', configured: 'Configured', notConfigured: 'Not Configured',
    twoFactor: 'Two-Factor Authentication', twoFactorDesc: 'Link a secondary verification method for sensitive actions and account recovery.', emailVerification: 'Email Verification', emailVerificationDesc: 'Used for login verification and password recovery', activated: 'Active', notActivated: 'Inactive', bind: 'Bind', googleAuthenticator: 'Google Authenticator', googleDesc: 'Enable enhanced account security after binding', emailRequired: 'Bind and activate an email address before continuing.',
  },
  email: {
    unbound: 'No email address is currently linked to your account.', bound: 'Current email address:', newAddress: 'New Email Address', invalid: 'Enter a valid email address',
    newPlaceholder: "Enter a new email address, for example: *****{'@'}gmail.com", code: 'Verification Code', codePlaceholder: 'Enter the verification code', codeAfterEmail: 'Enter an email address to request a verification code',
    changeTitle: 'Change Email Address', save: 'Save', bindSuccess: 'Email address linked successfully', bindFailed: 'Unable to link the email address', changeSuccess: 'Email address changed successfully', changeFailed: 'Unable to update the email address',
    verifyTitle: 'Email Verification', verifyDescription: 'We sent a 6-digit verification code to {email}. Enter it below to complete verification.', securityFooter: '{siteName} Security Verification · Protecting Your Account', securityTitle: 'Security Verification', submit: 'Submit', googleClosed: 'Google Authenticator disabled successfully', googleCloseFailed: 'Unable to disable Google Authenticator',
  },
  password: {
    old: 'Current Password', new: 'New Password', confirm: 'Confirm Password', length: 'Enter a password containing 6-32 characters', oldPlaceholder: 'Enter your current password', newPlaceholder: 'Enter a new password', confirmPlaceholder: 'Enter the new password again', mismatch: 'The passwords do not match', title: 'Change Password', submit: 'Submit', success: 'Password changed successfully. Please log in again.', failed: 'Unable to change the password',
  },
  ipWhitelist: { duplicate: 'Duplicate entry found: {ip}', title: 'Edit IP Allowlist', save: 'Save', success: 'IP allowlist updated successfully', failed: 'Unable to update the IP allowlist' },
  google: {
    bind: 'Bind', downloadStep: 'Download Authenticator', scanStep: 'Scan QR Code', verifyStep: 'Security Verification', downloadTip: 'Download and install Google Authenticator', android: 'Android Version', ios: 'iOS Version',
    scanDownload: 'Scan the QR code with your phone to download Google Authenticator', addAccount: 'Scan the QR code below with Google Authenticator, or enter the secret key manually to add the account.', rebindWarning: 'If you bind Google Authenticator again, the previous authenticator will no longer work.',
    manualCode: 'Scan the QR code or enter this code manually:', copy: 'Copy', enterCodeTip: 'Enter the 6-digit code generated by Google Authenticator to complete setup', codePlaceholder: 'Enter the 6-digit Google Authenticator code',
    keyCopied: 'Secret key copied to the clipboard', invalidCode: 'Enter a 6-digit verification code', bindSuccess: 'Google Authenticator linked successfully', title: 'Bind Google Authenticator',
  },
  loginRecords: {
    title: 'Login Devices', description: 'View currently signed-in devices and manage their login status.', unknownDevice: 'Unknown Device', currentDevice: 'Current Device', currentLogin: 'Currently Signed In', currentSession: 'Current Session', unknownBrowser: 'Unknown Browser', ipAddress: 'IP Address', loginTime: 'Login Time', offline: 'Sign Out', empty: 'No other signed-in devices',
    loadFailed: 'Unable to load login devices. Please contact support.', confirmTitle: 'Sign out this device?', confirmContent: 'This device will need to sign in again.', confirm: 'Confirm', cancel: 'Cancel', submitting: 'Submitting', success: 'Operation completed', offlineSuccess: 'Device signed out successfully', failed: 'Operation failed',
  },
}
